#6: add --qif cli option
ArtS/nab-export pull request #7
Opened 2017-10-05 03:51 UTC by tomquirk

see what you think @ArtS. Verryyy simple CLI arg implementation. Probably fine for now and it wouldn't be hard to extend slightly if needed.

2017-10-05 05:22 UTC, ArtS commented
Hey @tomquirk , QIF is kind of the default operating mode, any reason for turning that into a parameter?

2017-10-05 05:28 UTC, tomquirk commented
For myself at least, I don't need the QIF features, only the sqlite stuff. Basically I'd prefer to not have QIF files created in the first place instead of deleting them manually.

An easy compromise would be to have it export QIF by default and add an arg `--qif=false` to turn it off

2017-10-05 05:38 UTC, ArtS commented
Totally see the point & the use case, I suppose I am just cautious not to break existing behaviour. Would adding `--qif=false` or `--no-qif` work for you?

2017-10-05 05:43 UTC, tomquirk commented
yea will do 😄

2017-10-05 05:53 UTC, tomquirk commented
@ArtS there ya go

2017-10-05 06:00 UTC, parxier requested changes

2017-10-05 06:00 UTC, parxier commented on README.md
> +nab-export exports all of your transactions for all your NAB accounts. Using the `--qif` option, you can load exported QIF files into your desktop or online accounting software, such as Quicken/MS Mo
Wording will need to be changed to incorporate `--no-qif` switch now.

2017-10-05 06:11 UTC, ArtS commented on README.md
> +nab-export exports all of your transactions for all your NAB accounts. Using the `--qif` option, you can load exported QIF files into your desktop or online accounting software, such as Quicken/MS Mo
Good point, thanks браж

2017-10-05 06:13 UTC, parxier commented on README.md
> +nab-export exports all of your transactions for all your NAB accounts. Using the `--qif` option, you can load exported QIF files into your desktop or online accounting software, such as Quicken/MS Mo
тамбовский :wolf: тебе браж

2017-10-05 21:30 UTC, tomquirk commented
@parxier thanks for that 😄 @ArtS

2017-10-09 01:22 UTC, ArtS approved these changes

2017-10-09 01:23 UTC, merged